### ISSUE TITLE
Create new navbar

### ISSUE THREAD

**Issue by muruw** [MarekMurumae/HomeBar#5]
Current navbar doesn't work correctly. If we have too many list items in screen, then it won't fill the entire page with navbar. Also, if I click on "Recipes", then the word "Ingredients" is still active.

---

url says recipes but navbar has "ingredients" as an active item (purple)
![image](https://user-images.githubusercontent.com/35424371/221410235-0c8ed988-6dc7-4a9b-93f8-2e0ed964d376.png)

Too many items:
![image](https://user-images.githubusercontent.com/35424371/221410283-c0c3d704-411e-45ef-9c95-ab178134b6af.png)

**Comment by MarekMurumae** [comment]
Merge of another issue seems to have deleted the change
